DROP SCHEMA IF EXISTS notification CASCADE;
DROP SCHEMA IF EXISTS progress CASCADE;
DROP SCHEMA IF EXISTS review CASCADE;
DROP SCHEMA IF EXISTS scheduling CASCADE;
DROP SCHEMA IF EXISTS vocabulary CASCADE;
DROP SCHEMA IF EXISTS identity CASCADE;
